url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Lawrence Borst Blog" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
# Version number
build: 20180220